### ISSUE TITLE
Plottings

### ISSUE THREAD

**Issue by harry-cpp** [picoe/Eto.Toolkit#3]
Original issue: https://github.com/picoe/Eto/issues/589

**Comment by greatawesome** [comment]
I've added Eto support to ZedGraph in this fork: https://github.com/greatawesome/ZedGraph

Another alternative is ScottPlot also has an Eto control: https://github.com/ScottPlot/ScottPlot

**Comment by cwensley** [comment]
I think this can be closed with all of the options we have now.  Thanks to @greatawesome and @rafntor for getting all these wired up.
