### ISSUE TITLE
OpenGL Render Control

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto.Toolkit#7]
Original issue: https://github.com/picoe/Eto/issues/39

**Comment by cwensley** [comment]
We have permission to copy over https://github.com/philstopford/etoViewport, but it should probably be renamed to Eto.OpenTK as it won't work with any other libs.

**Comment by cra0zy** [comment]
PS. I tried OpenGL.Net on Linux, couldn't get it working...

**Comment by cwensley** [comment]
@cra0zy oh good to know.  Is it just when it is running in .NET Core, or does it also bork with mono?

**Comment by cra0zy** [comment]
.NET Core for now, have not tried mono,

**Comment by SpiceyWolf** [comment]
lmao crazy do u literally participate in everything .net/graphics related? i keep seeing u show up in the weirdest places xD

**Comment by SpiceyWolf** [comment]
also correct me if im wrong, but cant a wrapper lib be made for the control similar to the winforms otk control? i know its capable of a handle injection somewhat like sfml does for forms integration and i applied basicly that same principal to wrapping eto with a sfml control in a project i made a while back - prior to the monogame eto control i made lol

**Comment by cwensley** [comment]
Moved @philstopford's etoViewport repo to https://github.com/picoe/Eto.OpenTK
